#!/bin/bash

FQDN=`hostname -f`
REMOTE=$1

if [[ -z "$REMOTE" ]]
then
  echo "A remote host to connect to for debugging must be provided."
  echo "Example: drush-debug.sh example.lan"
  exit 1
fi

export PHP_IDE_CONFIG="serverName=$FQDN"
export XDEBUG_CONFIG="idekey=PHPSTORM remote_host=$REMOTE"

echo "PHP_IDE_CONFIG="$PHP_IDE_CONFIG
echo "XDEBUG_CONFIG="$XDEBUG_CONFIG

echo "Starting a new shell with xdebug enabled. Exit the shell to disable debugging."
bash
