#!/bin/bash

function pct_used() {
  df --output=pcent . | tail -n 1 | cut -c -3
}

function cleanup() {
  rm $ZERO
  exit
}

trap cleanup SIGINT

echo "Zeroing free space on the current disk."

ZERO=$(mktemp --tmpdir=.)
INITIAL=$(pct_used)

while [[ $(pct_used) -lt 99 ]]
do
  dd if=/dev/zero of=$ZERO \
    oflag=append conv=notrunc \
    bs=1024 count=10240 \
    status=none

  if [[ $PCT -ne $(pct_used) ]]
  then
    PCT=$(pct_used)
    REMAIN=$(echo "scale = 2; ($PCT - $INITIAL) / (99 - $INITIAL) * 100 / 1" | bc | awk -F. '{print $1}')
    echo -ne "\e[0K\r$REMAIN% complete..."
  fi
done

echo " zeroing complete."
